<?php
/**
 * AugmentationApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Semanticwrap
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SEMANTIC WRAPPER API
 *
 * To answer any query about your data
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Semanticwrap\semanticwrap;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Semanticwrap\ApiException;
use Semanticwrap\Configuration;
use Semanticwrap\HeaderSelector;
use Semanticwrap\ObjectSerializer;

/**
 * AugmentationApi Class Doc Comment
 *
 * @category Class
 * @package  Semanticwrap
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AugmentationApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'asyncAugment' => [
            'application/json',
        ],
        'augment' => [
            'application/json',
        ],
        'augmentByUrls' => [
            'application/json',
        ],
        'chatAugment' => [
            'application/json',
        ],
        'complexAugment' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation asyncAugment
     *
     * Answers a given query from the documents in the index
     *
     * @param  string $index_name index_name (required)
     * @param  \Semanticwrap\Model\CompletionQuery $payload payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['asyncAugment'] to see the possible values for this operation
     *
     * @throws \Semanticwrap\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Semanticwrap\Model\AsyncProcessResponse
     */
    public function asyncAugment($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['asyncAugment'][0])
    {
        list($response) = $this->asyncAugmentWithHttpInfo($index_name, $payload, $error_on_empty_docs, $with_source, $contentType);
        return $response;
    }

    /**
     * Operation asyncAugmentWithHttpInfo
     *
     * Answers a given query from the documents in the index
     *
     * @param  string $index_name (required)
     * @param  \Semanticwrap\Model\CompletionQuery $payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['asyncAugment'] to see the possible values for this operation
     *
     * @throws \Semanticwrap\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Semanticwrap\Model\AsyncProcessResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function asyncAugmentWithHttpInfo($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['asyncAugment'][0])
    {
        $request = $this->asyncAugmentRequest($index_name, $payload, $error_on_empty_docs, $with_source, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Semanticwrap\Model\AsyncProcessResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Semanticwrap\Model\AsyncProcessResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Semanticwrap\Model\AsyncProcessResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Semanticwrap\Model\AsyncProcessResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Semanticwrap\Model\AsyncProcessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation asyncAugmentAsync
     *
     * Answers a given query from the documents in the index
     *
     * @param  string $index_name (required)
     * @param  \Semanticwrap\Model\CompletionQuery $payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['asyncAugment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function asyncAugmentAsync($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['asyncAugment'][0])
    {
        return $this->asyncAugmentAsyncWithHttpInfo($index_name, $payload, $error_on_empty_docs, $with_source, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation asyncAugmentAsyncWithHttpInfo
     *
     * Answers a given query from the documents in the index
     *
     * @param  string $index_name (required)
     * @param  \Semanticwrap\Model\CompletionQuery $payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['asyncAugment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function asyncAugmentAsyncWithHttpInfo($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['asyncAugment'][0])
    {
        $returnType = '\Semanticwrap\Model\AsyncProcessResponse';
        $request = $this->asyncAugmentRequest($index_name, $payload, $error_on_empty_docs, $with_source, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'asyncAugment'
     *
     * @param  string $index_name (required)
     * @param  \Semanticwrap\Model\CompletionQuery $payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['asyncAugment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function asyncAugmentRequest($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['asyncAugment'][0])
    {

        // verify the required parameter 'index_name' is set
        if ($index_name === null || (is_array($index_name) && count($index_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $index_name when calling asyncAugment'
            );
        }

        // verify the required parameter 'payload' is set
        if ($payload === null || (is_array($payload) && count($payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payload when calling asyncAugment'
            );
        }




        $resourcePath = '/augmentation/async/augment/{index_name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $error_on_empty_docs,
            'error_on_empty_docs', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $with_source,
            'with_source', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($index_name !== null) {
            $resourcePath = str_replace(
                '{' . 'index_name' . '}',
                ObjectSerializer::toPathValue($index_name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($payload));
            } else {
                $httpBody = $payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation augment
     *
     * Answers a given query from the documents in the index
     *
     * @param  string $index_name index_name (required)
     * @param  \Semanticwrap\Model\CompletionQuery $payload payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['augment'] to see the possible values for this operation
     *
     * @throws \Semanticwrap\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Semanticwrap\Model\CompletionResponse|\Semanticwrap\Model\Error
     */
    public function augment($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['augment'][0])
    {
        list($response) = $this->augmentWithHttpInfo($index_name, $payload, $error_on_empty_docs, $with_source, $contentType);
        return $response;
    }

    /**
     * Operation augmentWithHttpInfo
     *
     * Answers a given query from the documents in the index
     *
     * @param  string $index_name (required)
     * @param  \Semanticwrap\Model\CompletionQuery $payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['augment'] to see the possible values for this operation
     *
     * @throws \Semanticwrap\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Semanticwrap\Model\CompletionResponse|\Semanticwrap\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function augmentWithHttpInfo($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['augment'][0])
    {
        $request = $this->augmentRequest($index_name, $payload, $error_on_empty_docs, $with_source, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Semanticwrap\Model\CompletionResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Semanticwrap\Model\CompletionResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Semanticwrap\Model\CompletionResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Semanticwrap\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Semanticwrap\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Semanticwrap\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Semanticwrap\Model\CompletionResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Semanticwrap\Model\CompletionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Semanticwrap\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation augmentAsync
     *
     * Answers a given query from the documents in the index
     *
     * @param  string $index_name (required)
     * @param  \Semanticwrap\Model\CompletionQuery $payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['augment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function augmentAsync($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['augment'][0])
    {
        return $this->augmentAsyncWithHttpInfo($index_name, $payload, $error_on_empty_docs, $with_source, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation augmentAsyncWithHttpInfo
     *
     * Answers a given query from the documents in the index
     *
     * @param  string $index_name (required)
     * @param  \Semanticwrap\Model\CompletionQuery $payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['augment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function augmentAsyncWithHttpInfo($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['augment'][0])
    {
        $returnType = '\Semanticwrap\Model\CompletionResponse';
        $request = $this->augmentRequest($index_name, $payload, $error_on_empty_docs, $with_source, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'augment'
     *
     * @param  string $index_name (required)
     * @param  \Semanticwrap\Model\CompletionQuery $payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['augment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function augmentRequest($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['augment'][0])
    {

        // verify the required parameter 'index_name' is set
        if ($index_name === null || (is_array($index_name) && count($index_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $index_name when calling augment'
            );
        }

        // verify the required parameter 'payload' is set
        if ($payload === null || (is_array($payload) && count($payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payload when calling augment'
            );
        }




        $resourcePath = '/augmentation/augment/{index_name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $error_on_empty_docs,
            'error_on_empty_docs', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $with_source,
            'with_source', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($index_name !== null) {
            $resourcePath = str_replace(
                '{' . 'index_name' . '}',
                ObjectSerializer::toPathValue($index_name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($payload));
            } else {
                $httpBody = $payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation augmentByUrls
     *
     * Answers a given query from the documents in the index
     *
     * @param  \Semanticwrap\Model\UrlCrawlingAugmentationQuery $payload payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['augmentByUrls'] to see the possible values for this operation
     *
     * @throws \Semanticwrap\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Semanticwrap\Model\AsyncProcessResponse|\Semanticwrap\Model\Error
     */
    public function augmentByUrls($payload, string $contentType = self::contentTypes['augmentByUrls'][0])
    {
        list($response) = $this->augmentByUrlsWithHttpInfo($payload, $contentType);
        return $response;
    }

    /**
     * Operation augmentByUrlsWithHttpInfo
     *
     * Answers a given query from the documents in the index
     *
     * @param  \Semanticwrap\Model\UrlCrawlingAugmentationQuery $payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['augmentByUrls'] to see the possible values for this operation
     *
     * @throws \Semanticwrap\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Semanticwrap\Model\AsyncProcessResponse|\Semanticwrap\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function augmentByUrlsWithHttpInfo($payload, string $contentType = self::contentTypes['augmentByUrls'][0])
    {
        $request = $this->augmentByUrlsRequest($payload, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Semanticwrap\Model\AsyncProcessResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Semanticwrap\Model\AsyncProcessResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Semanticwrap\Model\AsyncProcessResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Semanticwrap\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Semanticwrap\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Semanticwrap\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Semanticwrap\Model\AsyncProcessResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Semanticwrap\Model\AsyncProcessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Semanticwrap\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation augmentByUrlsAsync
     *
     * Answers a given query from the documents in the index
     *
     * @param  \Semanticwrap\Model\UrlCrawlingAugmentationQuery $payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['augmentByUrls'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function augmentByUrlsAsync($payload, string $contentType = self::contentTypes['augmentByUrls'][0])
    {
        return $this->augmentByUrlsAsyncWithHttpInfo($payload, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation augmentByUrlsAsyncWithHttpInfo
     *
     * Answers a given query from the documents in the index
     *
     * @param  \Semanticwrap\Model\UrlCrawlingAugmentationQuery $payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['augmentByUrls'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function augmentByUrlsAsyncWithHttpInfo($payload, string $contentType = self::contentTypes['augmentByUrls'][0])
    {
        $returnType = '\Semanticwrap\Model\AsyncProcessResponse';
        $request = $this->augmentByUrlsRequest($payload, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'augmentByUrls'
     *
     * @param  \Semanticwrap\Model\UrlCrawlingAugmentationQuery $payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['augmentByUrls'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function augmentByUrlsRequest($payload, string $contentType = self::contentTypes['augmentByUrls'][0])
    {

        // verify the required parameter 'payload' is set
        if ($payload === null || (is_array($payload) && count($payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payload when calling augmentByUrls'
            );
        }


        $resourcePath = '/augmentation/complex-chain/urls';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($payload));
            } else {
                $httpBody = $payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation chatAugment
     *
     * Answers a given query from the documents in the index
     *
     * @param  string $index_name index_name (required)
     * @param  \Semanticwrap\Model\ChatCompletionQuery $payload payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatAugment'] to see the possible values for this operation
     *
     * @throws \Semanticwrap\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Semanticwrap\Model\CompletionResponse|\Semanticwrap\Model\Error
     */
    public function chatAugment($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['chatAugment'][0])
    {
        list($response) = $this->chatAugmentWithHttpInfo($index_name, $payload, $error_on_empty_docs, $with_source, $contentType);
        return $response;
    }

    /**
     * Operation chatAugmentWithHttpInfo
     *
     * Answers a given query from the documents in the index
     *
     * @param  string $index_name (required)
     * @param  \Semanticwrap\Model\ChatCompletionQuery $payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatAugment'] to see the possible values for this operation
     *
     * @throws \Semanticwrap\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Semanticwrap\Model\CompletionResponse|\Semanticwrap\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function chatAugmentWithHttpInfo($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['chatAugment'][0])
    {
        $request = $this->chatAugmentRequest($index_name, $payload, $error_on_empty_docs, $with_source, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Semanticwrap\Model\CompletionResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Semanticwrap\Model\CompletionResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Semanticwrap\Model\CompletionResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Semanticwrap\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Semanticwrap\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Semanticwrap\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Semanticwrap\Model\CompletionResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Semanticwrap\Model\CompletionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Semanticwrap\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation chatAugmentAsync
     *
     * Answers a given query from the documents in the index
     *
     * @param  string $index_name (required)
     * @param  \Semanticwrap\Model\ChatCompletionQuery $payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatAugment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatAugmentAsync($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['chatAugment'][0])
    {
        return $this->chatAugmentAsyncWithHttpInfo($index_name, $payload, $error_on_empty_docs, $with_source, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chatAugmentAsyncWithHttpInfo
     *
     * Answers a given query from the documents in the index
     *
     * @param  string $index_name (required)
     * @param  \Semanticwrap\Model\ChatCompletionQuery $payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatAugment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatAugmentAsyncWithHttpInfo($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['chatAugment'][0])
    {
        $returnType = '\Semanticwrap\Model\CompletionResponse';
        $request = $this->chatAugmentRequest($index_name, $payload, $error_on_empty_docs, $with_source, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chatAugment'
     *
     * @param  string $index_name (required)
     * @param  \Semanticwrap\Model\ChatCompletionQuery $payload (required)
     * @param  string $error_on_empty_docs If true, will return 400 error if no docs are found (optional)
     * @param  string $with_source If true, the source of the answer is returned (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatAugment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function chatAugmentRequest($index_name, $payload, $error_on_empty_docs = null, $with_source = null, string $contentType = self::contentTypes['chatAugment'][0])
    {

        // verify the required parameter 'index_name' is set
        if ($index_name === null || (is_array($index_name) && count($index_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $index_name when calling chatAugment'
            );
        }

        // verify the required parameter 'payload' is set
        if ($payload === null || (is_array($payload) && count($payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payload when calling chatAugment'
            );
        }




        $resourcePath = '/augmentation/chat/augment/{index_name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $error_on_empty_docs,
            'error_on_empty_docs', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $with_source,
            'with_source', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($index_name !== null) {
            $resourcePath = str_replace(
                '{' . 'index_name' . '}',
                ObjectSerializer::toPathValue($index_name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($payload));
            } else {
                $httpBody = $payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation complexAugment
     *
     * Answers a given query from the documents in the index
     *
     * @param  \Semanticwrap\Model\ComplexAugmentationWithDocs $payload payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['complexAugment'] to see the possible values for this operation
     *
     * @throws \Semanticwrap\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Semanticwrap\Model\AsyncProcessResponse|\Semanticwrap\Model\Error
     */
    public function complexAugment($payload, string $contentType = self::contentTypes['complexAugment'][0])
    {
        list($response) = $this->complexAugmentWithHttpInfo($payload, $contentType);
        return $response;
    }

    /**
     * Operation complexAugmentWithHttpInfo
     *
     * Answers a given query from the documents in the index
     *
     * @param  \Semanticwrap\Model\ComplexAugmentationWithDocs $payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['complexAugment'] to see the possible values for this operation
     *
     * @throws \Semanticwrap\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Semanticwrap\Model\AsyncProcessResponse|\Semanticwrap\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function complexAugmentWithHttpInfo($payload, string $contentType = self::contentTypes['complexAugment'][0])
    {
        $request = $this->complexAugmentRequest($payload, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Semanticwrap\Model\AsyncProcessResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Semanticwrap\Model\AsyncProcessResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Semanticwrap\Model\AsyncProcessResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\Semanticwrap\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Semanticwrap\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Semanticwrap\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Semanticwrap\Model\AsyncProcessResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Semanticwrap\Model\AsyncProcessResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Semanticwrap\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation complexAugmentAsync
     *
     * Answers a given query from the documents in the index
     *
     * @param  \Semanticwrap\Model\ComplexAugmentationWithDocs $payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['complexAugment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function complexAugmentAsync($payload, string $contentType = self::contentTypes['complexAugment'][0])
    {
        return $this->complexAugmentAsyncWithHttpInfo($payload, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation complexAugmentAsyncWithHttpInfo
     *
     * Answers a given query from the documents in the index
     *
     * @param  \Semanticwrap\Model\ComplexAugmentationWithDocs $payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['complexAugment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function complexAugmentAsyncWithHttpInfo($payload, string $contentType = self::contentTypes['complexAugment'][0])
    {
        $returnType = '\Semanticwrap\Model\AsyncProcessResponse';
        $request = $this->complexAugmentRequest($payload, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'complexAugment'
     *
     * @param  \Semanticwrap\Model\ComplexAugmentationWithDocs $payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['complexAugment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function complexAugmentRequest($payload, string $contentType = self::contentTypes['complexAugment'][0])
    {

        // verify the required parameter 'payload' is set
        if ($payload === null || (is_array($payload) && count($payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payload when calling complexAugment'
            );
        }


        $resourcePath = '/augmentation/complex-chain/docs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($payload)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($payload));
            } else {
                $httpBody = $payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
