<?php
/**
 * AIModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SEMANTIC WRAPPER API
 *
 * To answer any query about your data
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AIModelTest Class Doc Comment
 *
 * @category    Class
 * @description AIModel
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AIModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AIModel"
     */
    public function testAIModel()
    {
    }

    /**
     * Test attribute "embedding_class"
     */
    public function testPropertyEmbeddingClass()
    {
    }

    /**
     * Test attribute "embedding_model_name"
     */
    public function testPropertyEmbeddingModelName()
    {
    }

    /**
     * Test attribute "augmenting_class"
     */
    public function testPropertyAugmentingClass()
    {
    }

    /**
     * Test attribute "augmenting_model_name"
     */
    public function testPropertyAugmentingModelName()
    {
    }

    /**
     * Test attribute "embed_instruction"
     */
    public function testPropertyEmbedInstruction()
    {
    }

    /**
     * Test attribute "query_instruction"
     */
    public function testPropertyQueryInstruction()
    {
    }
}
