<?php
/**
 * AugmentationApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Semanticwrap
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SEMANTIC WRAPPER API
 *
 * To answer any query about your data
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Semanticwrap\Test\Api;

use \Semanticwrap\Configuration;
use \Semanticwrap\ApiException;
use \Semanticwrap\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AugmentationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Semanticwrap
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AugmentationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for augmentByUrls
     *
     * Answers a given query from the documents in the index.
     *
     */
    public function testAugmentByUrls()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for complexAugment
     *
     * Answers a given query from the documents in the index.
     *
     */
    public function testComplexAugment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memoryfullAugment
     *
     * Answers a given query from the documents in the index.
     *
     */
    public function testMemoryfullAugment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memorylessAsyncAugment
     *
     * Answers a given query from the documents in the index.
     *
     */
    public function testMemorylessAsyncAugment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memorylessAugment
     *
     * Answers a given query from the documents in the index.
     *
     */
    public function testMemorylessAugment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
