<?php
/**
 * FineTunedApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Semanticwrap
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SEMANTIC WRAPPER API
 *
 * To answer any query about your data
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Semanticwrap\Test\Api;

use \Semanticwrap\Configuration;
use \Semanticwrap\ApiException;
use \Semanticwrap\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FineTunedApiTest Class Doc Comment
 *
 * @category Class
 * @package  Semanticwrap
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FineTunedApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for listFineTunedModel
     *
     * Get fine tuned models.
     *
     */
    public function testListFineTunedModel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for memorylessAugmentV2
     *
     * Answers a given query from the documents in the index.
     *
     */
    public function testMemorylessAugmentV2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
