<?php
/**
 * SearchApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Semanticwrap
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SEMANTIC WRAPPER API
 *
 * To answer any query about your data
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Semanticwrap\Test\Api;

use \Semanticwrap\Configuration;
use \Semanticwrap\ApiException;
use \Semanticwrap\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SearchApiTest Class Doc Comment
 *
 * @category Class
 * @package  Semanticwrap
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SearchApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for search
     *
     * Get Related Documents from the index with ANN search.
     *
     */
    public function testSearch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchByVector
     *
     * Get Related Documents from the index with ANN search.
     *
     */
    public function testSearchByVector()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchDocsById
     *
     * Get Related Documents from the index with ANN search for given document id.
     *
     */
    public function testSearchDocsById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
